### ISSUE TITLE
Fix Metabolics Tutorial to use files in distribution 

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-models#102]
Tutorial for [Simulation Based Design to Reduce Metabolic Cost](https://simtk-confluence.stanford.edu:8443/display/OpenSim/Simulation-Based+Design+to+Reduce+Metabolic+Cost) uses a downloaded package from SimTK. The example should use files from the distribution. 

This PR requires (i) changes to the Confluence Documentation, and (ii) updates to the Models repo to ensure that tutorial functions as expected.

**Comment by chrisdembia** [comment]
We should discuss that in the daily sprint today.

**Comment by jenhicks** [comment]
Need someone to review the doc and example once we have a build with everything in it.
