### ISSUE TITLE
Update simtk Models and examples package

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-models#106]
Make a release for 4.0 that just includes the models not included in the distribution. 
Add a note that others can be found in the 4.0 distribution. 
Update links as needed on confluence doc.

**Comment by jimmyDunne** [comment]
The examples that use a Downloaded Package
- [Working with Static Optimization](https://simtk-confluence.stanford.edu:8443/display/OpenSim/Example+-+Estimating+Joint+Reaction+Loads)
- [Example - Estimating Joint Reaction Loads](https://simtk-confluence.stanford.edu:8443/display/OpenSim/Example+-+Estimating+Joint+Reaction+Loads)
- [Sky High: Coordinating Muscles for Optimal Jump Performance](https://simtk-confluence.stanford.edu:8443/display/OpenSim/Coordinating+Muscles+for+Optimal+Jump+Performance)

**Comment by jimmyDunne** [comment]
@jenhicks, if you can do a quick review (open the models and run a setup file) to check that that it all looks okay, then I will post to the SimTK as a new package a new release to the OpenSim Models and Examples package. I made a few minor edits to the packages (updated model Geometry paths for femurs and tibia's, adjusted pelvis_ty so the model wasn't underground). 

[OptimalJump.zip](https://github.com/opensim-org/opensim-models/files/2577084/OptimalJump.zip)
[StaticOpt_JointReaction.zip](https://github.com/opensim-org/opensim-models/files/2577062/StaticOpt_JointReaction.zip)
[WorkingWithStaticOptimization.zip](https://github.com/opensim-org/opensim-models/files/2577063/WorkingWithStaticOptimization.zip)

**Comment by jenhicks** [comment]
Thanks ... I will give these a spin.

**Comment by jenhicks** [comment]
The static optimization example worked as expected.

**Comment by jenhicks** [comment]
The joint reaction analysis files run (SO then Analyze with joint reaction analysis). Let me know if there is anything else to test. This one is pretty old and one we should think about updating one day (e.g., to use new outputs).

**Comment by jimmyDunne** [comment]
Load the model, run the setup_JointReaction.xml. 

There is nothing else but just example files at the moment, so if it runs it works.

**Comment by jenhicks** [comment]
OK ... thanks. I didn't test the optimal jump example extensively, but I was able to load the model and set-up a forward simulation with the default controls. I also tried loading an excitation layout file. Do you know if anyone tested this during our beta testing process?

**Comment by jenhicks** [comment]
I think it is OK to go ahead and update these on Simtk.

**Comment by jimmyDunne** [comment]
I don't think anyone tested the full results. Just if it worked out of the box (which it passed).

**Comment by jimmyDunne** [comment]
The zips have been put on SimTK and the links have been updated on Confluence.
