### ISSUE TITLE
right-hand rule for Rajagopal knee

### ISSUE THREAD

**Issue by kernalnet** [opensim-org/opensim-models#127]
Hi, 
I posted on the simTK forum but nobody answered.  https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=773&t=11781&p=33097&start=0&view=

So I ask it here:

Why don't the knees of the Rajagopal model follow the right-hand rule?

Unlike the gait_2392 or Hamner models, the knee flexion values of the Rajagopal model are positive but based on the right-hand rule it should be negative (the same as the above-mentioned models).

Your response would be greatly appreciated.
Regards

**Comment by tkuchida** [comment]
What "right-hand rule" are you referring to? The one I know requires reference frames to be defined such that

![](https://user-images.githubusercontent.com/4203505/79070728-a4874d00-7ca5-11ea-9ac8-21b93a80a111.png)

All reference frames in OpenSim are right-handed frames.

**Comment by kernalnet** [comment]
Hi Tom,
https://c-motion.com/v3dwiki/index.php/Right_Hand_Rule
Gait_2392 and Hamner models follow this rule but not Rajagopal.
This is Hamner:
![image](https://user-images.githubusercontent.com/38867713/79071121-2059b780-7cef-11ea-8961-986a81d0bb6f.png)

And this is Rajagopal:
![image](https://user-images.githubusercontent.com/38867713/79071153-4e3efc00-7cef-11ea-91c4-8fbf54e227c3.png)

**Comment by tkuchida** [comment]
The knees are defined differently, but this is not a violation of the right-hand rule. Please look at the reference frames in the GUI:

gait2392 | Rajagopal
---|---
![gait2392](https://user-images.githubusercontent.com/4203505/79071337-2b89f480-7ca9-11ea-89e2-a9ad7b91a20b.png) | ![Rajagopal](https://user-images.githubusercontent.com/4203505/79071300-01d0cd80-7ca9-11ea-8d51-3fba8a3798f1.png)

This is not a bug.

**Comment by kernalnet** [comment]
Thanks for your reply, 

Is that right image the Rajagopal? Because in the latest version of Rajagopal, the knee axes are exactly the same as gait_2392 (X forward, Y upward and Z lateral).
Although the axes of both models are the same, but the knee sagittal plane kinematic graphs become vice versa.
