### ISSUE TITLE
Gait10dof18musc Gastroc path causes knee extension moment arm

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-models#129]
@antoinefalisse noted that the gastroc path in the gait10dof18musc model causes a knee extension moment arm (when the knee is flexed).

On the left is gait2392; on the right is gait10dof18musc:

<img width="931" alt="image" src="https://user-images.githubusercontent.com/846001/81347368-d6a38900-9070-11ea-9e70-0dcff3db58de.png">

The gastroc path in gait10dof18musc appears to originate from the tibia, even though the first two path points are actually on the femur.

**Comment by jenhicks** [comment]
We use in this example:
https://simtk-confluence.stanford.edu/display/OpenSim/Simulation-Based+Design+to+Reduce+Metabolic+Cost

**Comment by antoinefalisse** [comment]
@jenhicks, would it make sense to adjust the gait10dof18musc model so that it exactly matches gait2392? I am worried that people use it for research purposes and end up making wrong conclusions. Thanks.

**Comment by jenhicks** [comment]
Thanks for bringing this up again @antoinefalisse ! 

@carmichaelong did you start to look into this? 

I added it to the milestone for OpenSim 4.2 and put it in the product backlog so that we at least don't lose track of it.

**Comment by carmichaelong** [comment]
I haven't taken a close look at it yet. I can verify if it's helpful, though I think @antoinefalisse had some pretty compelling and clear plots about this issue. I like the idea of adjusting the model to better match gait2392.

**Comment by jenhicks** [comment]
@carmichaelong can you review @antoinefalisse 's PR?
