### ISSUE TITLE
Rajagopal knee model

### ISSUE THREAD

**Issue by mrrezaie** [opensim-org/opensim-models#148]
Dear Experts,

I have a question about the knee joint defined in the Rajagopal model. Please find the attached video. I see that the red axis (X) is the axis of knee flexion/extension. Why does this axis rotate during knee flexion while it has linear function? If this is not the axis of knee flexion/extension, where is the real axis?

```
<TransformAxis name="rotation1">
	<coordinates>knee_angle_r</coordinates>
	<axis>1 0 0</axis>
	<LinearFunction name="function">
		<coefficients> 1 0</coefficients>
	</LinearFunction>
</TransformAxis>
```

https://drive.google.com/file/d/1ggu7mhpnkE5Gdby5asDk-TS35lY2u5LJ/view?usp=sharing

Any help is much appreciated.

Best Regards,
Mohammadreza

**Comment by jenhicks** [comment]
Please post any questions on our OpenSim user forum. Thank you!
