### ISSUE TITLE
Unify updates to the `Rajagopal2015.osim` model

### ISSUE THREAD

**Issue by nickbianco** [opensim-org/opensim-models#161]
Over the past several years, many have taken the base `Rajagopal2015.osim` model that we release and have made useful modifications to it. Some of these changes include:

- Adrian Lai and Allison Arnold modified the model [to support simulations involving high hip and knee flexion](https://simtk.org/projects/model-high-flex).
- Scott Uhlrich modified the model [to calibrate muscle passive force parameters and hip abductor paths](https://simtk.org/projects/fbmodpassivecal).

It would be great to unify all valuable changes to the model and distribute it with OpenSim. We would need to check with the original authors of each change to see if directly incorporating their changes is okay with them (since they might lose download statistics on their SimTK.org projects). 

As of writing this I realized that we do not even distribute the original Rajagopal model in our own releases ([only on SimTK.org](https://simtk.org/projects/full_body)), so we'd need to decide what makes sense for those download stats too.

**Comment by aymanhab** [comment]
@nickbianco any news on the updated Rajagopal model? Thank you

**Comment by nickbianco** [comment]
Working with Scott U. to get an updated model, probably by mid next week.
