### ISSUE TITLE
Why .vtp files includes polygons with more than 3 egdes?

### ISSUE THREAD

**Issue by Ipuch** [opensim-org/opensim-models#162]
Hi,

I was wondering why .vtp files includes polygons with more 3 edges. I have been playing with them recently and figure out there was up to 12 edges for some polygons? Not only that, but I had to write a code to resmesh these polygons into triangles would be interested that I push the .vtp files remeshed ?

Regards,

Pierre

**Comment by aymanhab** [comment]
@Ipuch This is not a bug or issue, some mesh formats support only triangles, others quads, other use more sides if planar as long as the format can read/write/compute-normals there's no issue here.
