### ISSUE TITLE
Issues regarding wrist motions and publications in `RajagopalLaiUhlrich2023` model

### ISSUE THREAD

**Issue by mrrezaie** [opensim-org/opensim-models#168]
Hi, the newly released `RajagopalLaiUhlrich2023` model lacks wrist motions compared to the original model. Also, when re-saving the model, only the first publication element remains: https://github.com/opensim-org/opensim-models/pull/167

**Comment by aymanhab** [comment]
@nickbianco if you can indicate if this was intentional, and the rationale behind it would be great. Thank you

**Comment by nickbianco** [comment]
@aymanhab, no this was not intentional. I'll make a PR for this #167 before the full 4.5 release.
