### ISSUE TITLE
The tibia vtp files are incorrectly named

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-models#2]
Glen Litchtwark noticed that the left and right tibia visual geometry are on the wrong legs. I confirmed this as correct. Looks like the tibia.vtp and l_tibia.vtp are mislabeled.

**Comment by tkuchida** [comment]
Which model(s)?

**Comment by jimmyDunne** [comment]
This was noticed on the gait2392 model

**Comment by jimmyDunne** [comment]
opensim-org/opensim-core#219

**Comment by jimmyDunne** [comment]
Tom and I investigated this and this had not got fixed. The closed, but not merged PR, is here #3.
