### ISSUE TITLE
Update models that we distribute with the GUI so that they don't appear under the floor on first load.

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-models#36]

**Comment by jenhicks** [comment]
OK to hold until you're back in November

**Comment by tkuchida** [comment]
The following models were exhumed in PR #42 (per #39):
- 6 models in Gait10dof18musc directory
- 2 models in Gait2354_Simbody directory (not gait2354_with_pat_lig.osim as it looks like that model is already above ground—though I was unable to confirm in 4.0)
- 5 models in Gait2392_Simbody directory
- double_pendulum.osim in Pendulum directory

Should arm26 be moved up as well?

**Comment by nickbianco** [comment]
The ToyDropLanding models should be moved up as well: the contact platform sits below the floor if a floor texture is enabled.

**Comment by tkuchida** [comment]
Didn't realize there was already a old Issue for this. Closing; see Issue #56.
