### ISSUE TITLE
Convert binary .vtp files to ascii format for all models

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-models#38]
From [opensim-core closed issue #1976](https://github.com/opensim-org/opensim-core/issues/1976) 

Example models (Rajagopal2015, Hamner2010).

@tkuchida commented on Sat Aug 05 2017

Where possible, we should replace binary vtp files with geometry that can be loaded, particularly for these popular models. Sports.osim is another example (mentioned in #334).

@chrisdembia commented on Thu Aug 31 2017

Python script to convert file formats with VTP: https://gist.github.com/thomasballinger/1281457

**Comment by chrisdembia** [comment]
I wrote the following python script to convert `hat_ribs_scap.vtp` to ASCII:

```python
import sysimport vtk
reader = vtk.vtkXMLPolyDataReader()
reader.SetFileName(sys.argv[1])
writer = vtk.vtkXMLPolyDataWriter()
#writer = vtk.vtkSTLWriter()
writer.SetFileName(sys.argv[2])
writer.SetInputConnection(reader.GetOutputPort())
writer.SetDataModeToAscii()
writer.Write()
```

I had to get the python vtk package using `brew install vtk`.

Some reference links:
- https://www.vtk.org/Wiki/VTK/Examples/Cxx/IO/WriteVTP
- https://lorensen.github.io/VTKExamples/site/Python/IO/STLWriter/
- https://www.vtk.org/doc/nightly/html/classvtkXMLPolyDataWriter.html
- https://github.com/nipy/dipy/blob/master/dipy/viz/utils.py


The only other binary vtp files in the Geometry folder are the following:

- ConePendulum.vtp
- linkage1.vtp
- big_block_centered.vtp
- pendulum.vtp
