### ISSUE TITLE
SoccerKickingModel fails to open

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-models#41]
Multiple warnings due to space in model name (likely common), then failure/abort open due to Error
<img width="542" alt="screen shot 2017-11-08 at 9 58 18 am" src="https://user-images.githubusercontent.com/3972208/32565326-9863af5e-c46b-11e7-8cf2-bb5f8a9dcc29.png">

**Comment by tkuchida** [comment]
Possibly related to [1970 on opensim-core](https://github.com/opensim-org/opensim-core/issues/1970).

**Comment by tkuchida** [comment]
Issue moved to [opensim-org/opensim-core #2024](https://github.com/opensim-org/opensim-core/issues/2024) via [**ZenHub**](https://www.zenhub.com/)
