### ISSUE TITLE
Models\Gait2354_Simbody\gait2354_with_pat_lig.osim fails to open

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-models#43]
@tkuchida commented on [Mon Nov 13 2017](https://github.com/opensim-org/opensim-gui/issues/444)

Encountered when trying to fix https://github.com/opensim-org/opensim-models/pull/39.

Red-circle message:
<pre>
java.lang.RuntimeException: ArrayPtrs.get: Array index out of bounds.
	at org.opensim.modeling.opensimSimulationJNI.SetPathPoint_get__SWIG_0(Native Method)
	at org.opensim.modeling.SetPathPoint.get(SetPathPoint.java:145)
	at org.opensim.threejs.ModelVisualizationJson.createJsonForGeometryPath(ModelVisualizationJson.java:632)
	at org.opensim.threejs.ModelVisualizationJson.processDecorationsForComponent(ModelVisualizationJson.java:226)
	at org.opensim.threejs.ModelVisualizationJson.createJsonForModel(ModelVisualizationJson.java:197)
	at org.opensim.threejs.ModelVisualizationJson.<init>(ModelVisualizationJson.java:159)
	at org.opensim.view.pub.ViewDB.getJsonForModel(ViewDB.java:1764)
	at org.opensim.view.pub.ViewDB.update(ViewDB.java:423)
	at java.util.Observable.notifyObservers(Observable.java:159)
	at org.opensim.view.pub.OpenSimDB.addModel(OpenSimDB.java:153)
	at org.opensim.view.pub.OpenSimDB.addModel(OpenSimDB.java:141)
	at org.opensim.view.FileOpenOsimModelAction$2.run(FileOpenOsimModelAction.java:98)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
</pre>

Messages window:
<pre>
Updating Model file from 20302 to latest format...
Loaded model gait2354withLigament from file C:\Users\lordt_000\Documents\opensim-models\Models\Gait2354_Simbody\gait2354_with_pat_lig.osim
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_2'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_3'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_2'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_2'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_2'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_2'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_2'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_2'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_2'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_2'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_3'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_2'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_2'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_2'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_2'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_2'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_2'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_2'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
Model 'gait2354withLigament' has subcomponents with duplicate name 'hip_r'.
The duplicate is being renamed to 'hip_r_0'.
Model 'gait2354withLigament' has subcomponents with duplicate name 'hip_l'.
The duplicate is being renamed to 'hip_l_0'.
Model 'gait2354withLigament' has subcomponents with duplicate name 'knee_r'.
The duplicate is being renamed to 'knee_r_0'.
Model 'gait2354withLigament' has subcomponents with duplicate name 'ankle_r'.
The duplicate is being renamed to 'ankle_r_0'.
Model 'gait2354withLigament' has subcomponents with duplicate name 'knee_l'.
The duplicate is being renamed to 'knee_l_0'.
Model 'gait2354withLigament' has subcomponents with duplicate name 'ankle_l'.
The duplicate is being renamed to 'ankle_l_0'.
</pre>

---

@tkuchida commented on [Mon Nov 13 2017](https://github.com/opensim-org/opensim-gui/issues/444#issuecomment-344160595)

Confirmed that the model opens using the API, so presumably this is not an opensim-core issue.

**Code**
```cpp
Model* model = new Model("gait2354_with_pat_lig.osim");
SimTK::State& s = model->initSystem();
```

**Output**
<pre>
Updating Model file from 20302 to latest format...
Loaded model gait2354withLigament from file gait2354_with_pat_lig.osim
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_2'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_3'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_2'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_2'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_2'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_2'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_2'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_2'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_2'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_2'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_3'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_2'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_2'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_2'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_2'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_2'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_2'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_2'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_1'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathpoint'.
The duplicate is being renamed to 'pathpoint_0'.
Model 'gait2354withLigament' has subcomponents with duplicate name 'hip_r'.
The duplicate is being renamed to 'hip_r_0'.
Model 'gait2354withLigament' has subcomponents with duplicate name 'hip_l'.
The duplicate is being renamed to 'hip_l_0'.
Model 'gait2354withLigament' has subcomponents with duplicate name 'knee_r'.
The duplicate is being renamed to 'knee_r_0'.
Model 'gait2354withLigament' has subcomponents with duplicate name 'ankle_r'.
The duplicate is being renamed to 'ankle_r_0'.
Model 'gait2354withLigament' has subcomponents with duplicate name 'knee_l'.
The duplicate is being renamed to 'knee_l_0'.
Model 'gait2354withLigament' has subcomponents with duplicate name 'ankle_l'.
The duplicate is being renamed to 'ankle_l_0'.
Press any key to continue . . .
</pre>

---

@aymanhab commented on [Tue Nov 14 2017](https://github.com/opensim-org/opensim-gui/issues/444#issuecomment-344194399)

    <Ligament name="pat_lig_r">
					<isDisabled> false </isDisabled>
					<GeometryPath name="">
						<PathPointSet name="">
							<objects/>
							<groups/>
						</PathPointSet>
						<VisibleObject name="">
							
							<GeometrySet name="">
								<objects/>
								<groups/>
							</GeometrySet>
							
							<scale_factors>       1.00000000       1.00000000       1.00000000 </scale_factors>
							
							<transform>      -0.00000000       0.00000000      -0.00000000       0.00000000       0.00000000       0.00000000 </transform>
							
							<show_axes> false </show_axes>
							
							<display_preference> 4 </display_preference>
						</VisibleObject>
						<PathWrapSet name="">
							<objects/>
							<groups/>
						</PathWrapSet>
					</GeometryPath>
Empty PathPointSet s are not supported

---

@tkuchida commented on [Tue Nov 14 2017](https://github.com/opensim-org/opensim-gui/issues/444#issuecomment-344196360)

Interesting. The GeometryPath has no attachments—I should have noticed that. Is this model supposed to be in the repo?

![geometrypath](https://user-images.githubusercontent.com/4203505/32772488-db652cf6-c8da-11e7-99e9-0e2e3bc8df22.png)

**Comment by tkuchida** [comment]
@jimmyDunne Are you familiar with this model?

**Comment by tkuchida** [comment]
What are the plans for this model? @jimmyDunne @aseth1

**Comment by aseth1** [comment]
@tkuchida I vote to remove from the repo. It is not distributed with 3.3, so I am not sure how it snuck in here. It apparently never really worked, either, since the ligament was never attached to anything.
@jimmyDunne @chrisdembia and reason to keep it?

**Comment by chrisdembia** [comment]
I don't know the history of this model and I don't think I can weigh in on whether or not to keep it.

Some thoughts:

- We do not "install" the model; it only sits in the repo. 
- In the testing script, we could add this model to a list of models to skip for testing.

**Comment by aseth1** [comment]
@jimmyDunne @jenhicks please vote to keep or remove. I vote to remove since it seems to be invalid without adequate path points to form the ligament path.

**Comment by jenhicks** [comment]
My vote is to remove it from this repo.

**Comment by jimmyDunne** [comment]
remove
