### ISSUE TITLE
Ensure all models are shown above the floor when loaded

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-models#56]
- [x] Models\Arm26\arm26.osim
- [x] Models\BouncingBlock\bouncing_block.osim
- [x] Models\BouncingBlock\bouncing_block_weak_spring.osim
- [x] Models\Gait10dof18musc\gait10dof18musc.osim
- [x] Models\Gait10dof18musc\subject01.osim
- [x] Models\Gait10dof18musc\subject01_metabolics.osim
- [x] Models\Gait10dof18musc\subject01_metabolics_path_actuator.osim
- [x] Models\Gait10dof18musc\subject01_metabolics_path_spring.osim
- [x] Models\Gait10dof18musc\subject01_metabolics_spring.osim
- [x] Models\Gait2354_Simbody\gait2354_simbody.osim
~~Models\Gait2354_Simbody\gait2354_with_pat_lig.osim~~ (removed from repo)
- [x] Models\Gait2354_Simbody\subject01_simbody.osim
- [x] Models\Gait2392_Simbody\gait2392_millard2012muscle.osim
- [x] Models\Gait2392_Simbody\gait2392_thelen2003muscle.osim
- [x] Models\Gait2392_Simbody\subject01.osim
- [x] Models\Gait2392_Simbody\subject01_adjusted.osim
- [x] Models\Gait2392_Simbody\subject01_simbody_adjusted.osim
- [x] Models\Jumper\DynamicJumperModel.osim
- [x] Models\Leg6Dof9Musc\leg6dof9musc.osim
- [x] Models\Pendulum\double_pendulum.osim
- [x] Models\SoccerKick\SoccerKickingModel.osim
- [x] Models\ToyLanding\ToyLandingModel.osim
- [x] Models\ToyLanding\ToyLandingModel_activeAFO.osim
- [x] Models\ToyLanding\ToyLandingModel_AFO.osim
- [x] Models\Tug_of_War\Tug_of_War.osim
- [x] Models\Tug_of_War\Tug_of_War_Millard.osim
- [x] Models\WristModel\wrist.osim
- [x] Pipelines\Gait10dof18musc\OutputReference\gait10dof18musc.osim
- [x] Pipelines\Gait10dof18musc\OutputReference\subject01.osim
- [x] Pipelines\Gait10dof18musc\OutputReference\CMC\subject01_metabolics.osim
- [x] Pipelines\Gait10dof18musc\OutputReference\CMC\subject01_metabolics_path_actuator.osim
- [x] Pipelines\Gait10dof18musc\OutputReference\CMC\subject01_metabolics_path_spring.osim
- [x] Pipelines\Gait10dof18musc\OutputReference\CMC\subject01_metabolics_spring.osim
- [x] Pipelines\Gait2354_Simbody\OutputReference\subject01_scaledOnly.osim
- [x] Pipelines\Gait2354_Simbody\OutputReference\subject01_simbody.osim
- [x] Pipelines\Gait2354_Simbody\OutputReference\subject01_simbody_adjusted.osim
- [x] Pipelines\Gait2392_Simbody\OutputReference\subject01_simbody.osim
- [x] Pipelines\Gait2392_Simbody\OutputReference\subject01_simbody_adjusted.osim
- [x] Tutorials\Computed_Muscle_Control\InverseKinematics\arm26.osim
- [x] Tutorials\Computed_Muscle_Control\OutputReference\arm26.osim
- [x] Tutorials\Computed_Muscle_Control\OutputReference\arm26_with_bucket.osim
- [x] Tutorials\Estimating_Joint_Reaction_Loads\subject01_simbody_adjusted_StaticOp.osim
- [x] Tutorials\Strength_of_Simulation\Stance\Reference\leg6dof9musc_added_mass.osim
- [x] Tutorials\Strength_of_Simulation\Stance\Reference\RRA\leg6dof9musc_adjusted.osim

**New models:**
- [ ] Models\RajagopalModel\Rajagopal2015.osim
- [ ] Pipelines\Rajagopal\outputReference\subject01_registered.osim
- [ ] Pipelines\Rajagopal\outputReference\subject01_RRA_Adjusted.osim
- [ ] Pipelines\Rajagopal\outputReference\subject01_scaled.osim

**Comment by tkuchida** [comment]
**Status**
- Models\Gait2354_Simbody\gait2354_with_pat_lig.osim – Issue #43
- Models\SoccerKick\SoccerKickingModel.osim – Issue #53
- 11 full-body models – PR #59
- 4 arm26 models – PR #61

**Comment by tkuchida** [comment]
Confirmed that all 43 models are displayed above the floor when opened in the 4.0 GUI. Tested with AppVeyor artifact OpenSim-de42e7ae-2018-03-10.zip.

**Comment by tkuchida** [comment]
@aymanhab I thought I had fixed them all and I think I opened them after merging to double-check, but please let me know if you've found another subterranean model and I will exhume it. :shovel:

**Comment by jenhicks** [comment]
On my Mac build, the arm26 in the models folder shows up in the middle of the ground. But this might also be due to an issue with my Models folder not being completely up to date. How does the arm26 appear on your latest build on windows, @tkuchida

**Comment by tkuchida** [comment]
@jenhicks There are (at least) 8 arm26 models you could be referring to. I just opened all 8 using AppVeyor artifact OpenSim-4077dd7b-2018-03-29.zip and they were all above ground.

**Four arm26 models are copied into a directory of my choosing by AppVeyor artifact OpenSim-4077dd7b-2018-03-29.zip:**
- Models and Scripts\Models\Arm26\arm26.osim
- Models and Scripts\Models\Arm26\InverseKinematics\arm26.osim
- Models and Scripts\Models\Arm26\OutputReference\arm26.osim
- Models and Scripts\Models\Arm26\OutputReference\arm26_with_bucket.osim

**Four models reside in my local clone of the opensim-models repo:**
- opensim-models\Models\Arm26\arm26.osim
- opensim-models\Tutorials\Computed_Muscle_Control\InverseKinematics\arm26.osim
- opensim-models\Tutorials\Computed_Muscle_Control\OutputReference\arm26.osim
- opensim-models\Tutorials\Computed_Muscle_Control\OutputReference\arm26_with_bucket.osim

Are there other arm26 models I need to modify?

**Comment by tkuchida** [comment]
**Note:** Above, I commented "Confirmed that all 43 models are displayed above the floor when opened in the 4.0 GUI. Tested with AppVeyor artifact OpenSim-de42e7ae-2018-03-10.zip." To clarify: I manually opened each model in the GUI and visually confirmed that they were all above ground.

**Comment by jenhicks** [comment]
Sorry for not being clear in my comment. Do you have one of the last couple builds of the GUI (downloaded from Simtk or one of the ones Ayman posted on dropbox) installed on your machine? If you navigate to the models installed with the GUI, does the arm26 model there appear above or below ground?

**Comment by tkuchida** [comment]
> Do you have one of the last couple builds of the GUI (downloaded from Simtk or one of the ones Ayman posted on dropbox) installed on your machine?

I tested with AppVeyor artifact OpenSim-4077dd7b-2018-03-29.zip.

**Comment by tkuchida** [comment]
> Do you have one of the last couple builds of the GUI (downloaded from Simtk or one of the ones Ayman posted on dropbox) installed on your machine?

No, I've been living off of AppVeyor artifacts. @aymanhab Please verify that you have pulled `master` from this repo into your workflow to update the models in the distribution.

**Comment by tkuchida** [comment]
> If you navigate to the models installed with the GUI, does the arm26 model there appear above or below ground?

I can test on my machine if you upload the model here, but I don't think there will be any difference in the position of the model when it's opened on different computers or on Mac vs. Windows.

**Comment by jenhicks** [comment]
OK ... it sounds like for some reason the Models that the GUI installed on my machine are not the latest ones.

**Comment by jenhicks** [comment]
@jimmyDunne Could you check out the Models folder (Documents/OpenSim/4.0.Beta is the location on my machine) the GUI installed on your Mac and see how the Arm26 model looks?

**Comment by jimmyDunne** [comment]
Below are the three models in the Arm26 folder opened in the 4.0 Beta GUI on Mac

![screen shot 2018-03-30 at 7 56 13 am](https://user-images.githubusercontent.com/5296507/38142094-ea763098-33ef-11e8-9e76-20a1fa809798.png)

**Comment by jenhicks** [comment]
@aymanhab It looks like the installers are not updating my models folder. Is this worth creating an issue for or am I special case since I have been installing many versions of the software?

**Comment by aymanhab** [comment]
Let me explain how this is supposed to work since it's going to be useful
to document for us and for all users:
-  distribution contains no individually editable models, instead it has a
zip file Resources.zip
- On first launch, application detects that resources need installation and
prompts user for location to unzip resources
- if user cancels, s/he could be left with stale resources, if not a fresh
copy is installed from the zip
- user can go back to reinstall resources from application by typing
installResources () at scripting shell.

Since we don't know what decisions were made on first launch, best action
would be to re "installResources" from our official posted distributions
and see what you get. If models are underground, open installation issue,
otherwise no need.

Hope this helps and thanks much Tom and James for all your help.

Ayman

**Comment by tkuchida** [comment]
> On first launch, application detects that resources need installation and prompts user for location to unzip resources

This statement conflicts with my experience. Until 1 or 2 weeks ago, each new AppVeyor artifact would prompt to install models and scripts when it was first run. I downloaded and unzipped the "2018-03-29" artifact yesterday and it did not prompt me to install models and scripts on first run.

**Comment by jenhicks** [comment]
I was able to run installResources() from the scripting shell and now the arm26 model is above ground. I will file an issue about updating documentation.
