### ISSUE TITLE
SoccerKickingModel visuals need updates/improvements prior to release

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-models#68]
Current issues:
- [ ] "there appear to be some overlapping planes (see, e.g., the floor and the side of the net, which flicker when rotating the camera):" -- @tkuchida 

- [x] Textures for grass and the soccer ball surfaces do not display. Perhaps they should be removed?

**Comment by aseth1** [comment]
Related to comments and remaining issues from #67

**Comment by tkuchida** [comment]
From AppVeyor artifact OpenSim-6826a797-2018-02-28.zip:
![](https://user-images.githubusercontent.com/4203505/37302629-4fe38e04-25e9-11e8-967c-c327f8f9a1da.png)

**Comment by tkuchida** [comment]
Very difficult to adjust camera to get close-up of foot (Visualizer lags, camera rotations are not intuitive, amount of zoom is inconsistent, etc.). Should be used as a test case for camera. 75fdf108-2018-05-11

**Comment by jimmyDunne** [comment]
Fixed in https://github.com/opensim-org/opensim-models/pull/115
