### ISSUE TITLE
Gait 2354 folder distributed with GUI does not include IK results in the output reference

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-models#70]
It seems it's not getting pulled in by cmake?

**Comment by jenhicks** [comment]
@chrisdembia Tagging you since I think you did the cmake gymnastics.

**Comment by chrisdembia** [comment]
Ah yes, I was ignoring this file. One issue is that there are two IK results in this repo: 

1. `Pipelines/Gait2354_Simbody/subject01_walk1_ik.mot`
2. `Pipelines/Gait2354_Simbody/OutputReference/subject01_walk1_ik.mot`

I just tried running scale and IK myself and neither of these files match the output I got.

File (2) matches the file `Models/Gait2354_Simbody/OutputReference/subject01_walk1_ik.mot` from the 3.3 installation.

Therefore, I'll install (2) into `Models/Gait2354_Simbody/OutputReference/subject01_walk1_ik.mot` and I'll ignore (1).

**Comment by jenhicks** [comment]
Thanks @chrisdembia. What are the differences between (2) and the output you got?

**Comment by chrisdembia** [comment]
Blue is the output I got.
Orange is (2)

![screen shot 2018-04-12 at 11 32 20 am](https://user-images.githubusercontent.com/846001/38696893-4b709a3c-3e45-11e8-83d7-90fb1a0b2a39.png)

Lumbar extension and the ankle angle are noticeably different (about 2 to 3 degrees). The subtalar angle looks different but it's essentially 0.

**Comment by chrisdembia** [comment]
The differences between (1) and (2) are even bigger than the differences between what I got and (2).

Blue is (1)
Orange is (2)


<img width="1426" alt="screen shot 2018-04-12 at 11 35 37 am" src="https://user-images.githubusercontent.com/846001/38697016-a187d53e-3e45-11e8-8157-605f2b1825c9.png">
