### ISSUE TITLE
Install Rajagopal2015 model.

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-models#86]
This repository contains the Rajagopal2015 model but this model is not installed, and therefore does not end up in the GUI distribution.

**Comment by jenhicks** [comment]
I think this was intentional. This way we can test that the model loads, etc. via automated testing. But users will still get the model via the simtk project so we can track its impact.

**Comment by tkuchida** [comment]
> so we can track its impact

There's at least one other project on simtk that perhaps should be included when establishing the impact of Apoorva's model: [A musculoskeletal model for simulations that involve high hip and knee flexion](https://simtk.org/projects/model-high-flex/).
