### ISSUE TITLE
Gait2392 coordinate and muscle asymmetry 

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-models#96]
It was reported by a user (confirmed) that gait2392 had different ranges of motion for the left and right ankle coordinates. 

There may be other asymmetries as I found an older bug report by Antoine Falisse; 

> I think we spotted a bug in the gait2392 model: the splines are different between the right and left sides for the vastus intermedius. I had a look on Github but the only thing I found was this example [here](https://github.com/opensim-org/opensim-core/blob/master/Bindings/Java/Matlab/examples/testData/Subject01/subject01_gait2392_scaled.osim) and I see that the splines for the right vast_int [here](https://github.com/opensim-org/opensim-core/blob/master/Bindings/Java/Matlab/examples/testData/Subject01/subject01_gait2392_scaled.osim#L4974) and for the lest vast_int [here](https://github.com/opensim-org/opensim-core/blob/master/Bindings/Java/Matlab/examples/testData/Subject01/subject01_gait2392_scaled.osim#L8473) are different.

**Comment by antoinefalisse** [comment]
@jimmyDunne, do you want me to issue a PR for the splines of the VI?

**Comment by jimmyDunne** [comment]
If you would like to, that would be awesome! 

To close this issue, I will write some automated tests that can live in this repo.

**Comment by aymanhab** [comment]
@jimmyDunne Do you anticipate making this change before 4.0? Because we'll need to update the version of the models repo that the GUI pulls if so

**Comment by jimmyDunne** [comment]
No, I don't. We will add it in the following sprint.

**Comment by antoinefalisse** [comment]
No prob @jimmyDunne, I will do the PR tomorrow.

**Comment by jimmyDunne** [comment]
PR to fix Gait2392 asymmetry has been accepted. However. to close this issue I need to write a test for the models. I will add it to a future sprint.
